CREATE TABLE [FEED].[Ignore]
(
	[Id] INT NOT NULL IDENTITY(1000, 1),
	[Cause] NVARCHAR(500) NOT NULL,
	[Type] INT DEFAULT 1 NOT NULL,
	CONSTRAINT [PK#FEED@Ignore@ID] PRIMARY KEY CLUSTERED ([Id] ASC),
)
